platform :ios, '7.0'

target 'ParallaxCarouselView_Example' do
  pod 'ParallaxCarouselView', :path => '../'

  target 'ParallaxCarouselView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
